### ISSUE TITLE
Tag releases in git

### ISSUE THREAD

**Issue by eharrow** [astlouys/Pico-Green-Clock#14]
Hi

Can I suggest that releases you are building after all your hard work are tagged?  It might be that the make file can be changed to do this or perhaps consider using GitHub actions to build from source (https://github.com/features/actions) and tag?

--Ewan

**Comment by astlouys** [comment]
Ewan,

Yes, I know this is something I should do... It's similar to testing I discussed in another section: so many things to add to the code and not enough time to properly test all of them and properly learn the GitHub environment...

I will take a look at the link you provided. There is a bug report that I want to solve quickly and I will try to use the tags as you suggest.

**Comment by astlouys** [comment]
Hello Ewan,

I just released Version 9.00 of the Green Clock Firmware.

I tried to tag it form the GitHub Web site and what I understood is that I must have a professional account (read: "$$$") to have the privileges required to put a tag (did I miss something ?)

So, I thought I would try from Git when making the commit of the new version, but I was told that password support was no more supported. I was referred to "Credential Manager" and / or "Personal Access Token" or the like. I may go through this when I have a lot of spare time ahead, but I didn't feel to do it now. I hope you'll be able to take advantage of the firmware without that for the short term...

André

**Comment by jvhaarst** [comment]
Weird, I just cloned your repo in the github website, and could create (after some struggle with the interface) a release from there.
The error I got at first was that the tag I used wasn't correct.
Turns out you need to create a tag _and_ a title for the release.

**Comment by astlouys** [comment]
Hi Jan,

That's strange, I never heard such a problem from another user...

Have you tried to simply build the executable from inside Visual Studio Code without any relation with GitHub (once you cloned the repository) ?

...and by the way, are you using Visual Studio Code ?  Under Windows or Linux ?

In the meantime, I would say that you can use one the ".uf2" versions that I put on GitHub.

Ewan, if you read us, I know that you've been able to build the code on your side... did you ever encounter this type of error ?

**Comment by jvhaarst** [comment]
Hi André,
I didn't have any trouble building (I didn't try yet).
I thought you wanted to tag and release V9 now that it is available, so that people can more easily track the releases.
I'll put v9 on my Green Clock tonight, by just putting the uf2 on it.

**Comment by astlouys** [comment]
Hi Jan,

I'm sorry, I misunderstood what you wanted to say.

In fact, I wasn't able to set a tag, so I'm not surprised that GitHub complaint about it... (smile). When I have a few minutes free, I'll take the time to read about "Credential Manager" and / or "Personal Access Token" to solve that. I suppose you use one of these yourself ?

**Comment by eharrow** [comment]
André

To create tags you would do this from a git client and then push to the remote in this case GitHub.  Using git from the command line you might do `git tag v0.9.1` and then push with `git push --tags`.  There are a couple of different type of tags - simple and annotated.

See https://www.atlassian.com/git/tutorials/inspecting-a-repository/git-tag

--Ewan

**Comment by astlouys** [comment]
Thank you for taking the time to send me this information, Ewan.

I won't do it now since I worked on the code since the last release (and the code is currently unstable), but I will try it for Version 10.00 release. (However, if I remember well, I did try the "push" and this is when I received the "missing privileges" message...)

Whatever the case, I will try it and let you know after reading instructions in the link you provided...

**Comment by eharrow** [comment]
> Thank you for taking the time to send me this information, Ewan.
> 
> I won't do it now since I worked on the code since the last release (and the code is currently unstable), but I will try it for Version 10.00 release. (However, if I remember well, I did try the "push" and this is when I received the "missing privileges" message...)
> 
> Whatever the case, I will try it and let you know after reading instructions in the link you provided...

If you want extra homework one can also tag old commits i.e. for the previous releases.  It is mentioned in those docs.

**Comment by astlouys** [comment]
Yes Ewan,

I've seen that "git log" list commits that have been done before. I will try a few of them. I don't know if it is worth it (I doubt that users will want to use version 3.00 any more now), but I will do it as an exercise...

Thanks for the info.
